### ISSUE TITLE
User reports data loss with this plugin

### ISSUE THREAD

**Issue by whitenoisedev** [isdmg/obsidian-remove-unused-block-ids#6]
A user reported a data loss with this plugin and that you deleted their issue on this repo. Can you shed some light on this situation?

https://forum.obsidian.md/t/remove-unused-block-ids-plug-in-has-a-deceptive-name/91674/2

**Comment by isdmg** [comment]
@whitenoisedev 
Hello. I deleted the issue because it was more focused on personal complaints directed at me rather than constructive suggestions or steps to address specific issues in this plugin.

I have the whole conversation in my email, which I am happy to share with you if needed.

Sample conversation:
![image](https://github.com/user-attachments/assets/376f553d-9be4-40a3-9e06-9ede2347e6de)

Additional info:
- I have warned the users of the risk of data loss that may occur when the plugin works unexpectedly since the first version of my plugin in my README.md
- I have warned the users of the limitations of my plugin in my README.md
- I have reviewed my code and found it impossible for the plugin to delete all embeds, as shown in the image
- I tried working with the person who created the issue and found them very unhelpful and rude. The conversation was not going anywhere, and they are unwilling to cooperate to guide me through the issues they are facing.

**Comment by isdmg** [comment]
Please note that I do not delete issues on a whim as they help me improve the quality of my plugin. See issue #1 #2 and #3 for examples.

**Comment by whitenoisedev** [comment]
Thank you for the quick reply. 
We are not interested in your message exchange with the user. 

We just wanted to make sure if there is a bug that causes data loss, that it would be addressed. 

Thanks

**Comment by isdmg** [comment]
Please rest assured that I am fully committed to addressing and resolving any issues users may encounter with this plugin. The issues submitted by the user were an exception, as they deviated from the topic and were unfortunately both unhelpful and rude.
